version: "3.8"

services:
  mc-server:
    image: itzg/minecraft-server
    ports:
      - 9090:25565
      - 9091:8123
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      SPIGET_RESOURCES: 80128,390
      MODS: https://mediafilez.forgecdn.net/files/3922/624/worldedit-bukkit-7.2.12.jar,https://mediafilez.forgecdn.net/files/3903/109/worldguard-bukkit-7.0.8-beta-01-dist.jar,https://mediafilez.forgecdn.net/files/3113/114/Multiverse-Portals-4.2.1.jar,https://mediafilez.forgecdn.net/files/3934/649/Dynmap-3.4-spigot.jar,https://mediafilez.forgecdn.net/files/4049/447/DropHeads.jar,https://mediafilez.forgecdn.net/files/3074/605/Multiverse-SignPortals-4.2.0.jar,https://mediafilez.forgecdn.net/files/3687/469/Multiverse-Inventories-4.2.3.jar
      JAVA_ARGS: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true"
    volumes:
      - ./minecraft-data:/data
    restart: always
