version: "3.8"

services:
  mc-server:
    image: itzg/minecraft-server
    ports:
      - 9090:25565
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      REMOVE_OLD_MODS: "TRUE"
      SPIGET_RESOURCES: 80128
      MODS: https://mediafilez.forgecdn.net/files/3922/624/worldedit-bukkit-7.2.12.jar,https://mediafilez.forgecdn.net/files/3903/109/worldguard-bukkit-7.0.8-beta-01-dist.jar
    volumes:
      - ./minecraft-data:/data
    restart: always