version: "3.8"

services:
  mc-server:
    image: itzg/minecraft-server
    ports:
      - 9090:25565
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      SPIGET_RESOURCES: 25080,31043,31054
    volumes:
      - ./minecraft-data:/data
    restart: always